### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by tuxsu** [divadsn/docker-deluge-ltconfig#1]
Do you have any plans on supporting ARM cpus in Docker? Thank you!🙏🏻

**Comment by divadsn** [comment]
I could try building the image on my Orange Pi Zero, should be possible.

**Comment by tuxsu** [comment]
> I could try building the image on my Orange Pi Zero, should be possible.

I used your source code and compiled the arm64 architecture docker images with basically no problems. Thank you!

**Comment by divadsn** [comment]
Great to hear! Sorry that I forgot to write you back 😅
